### ISSUE TITLE
a really really bad issue

### ISSUE THREAD

**Issue by knobbel3** [khemachat-sittiritkawin/myproject#1]
hi, i have a really really bad **issue**. there are also sub-issues that im having : 

1. an issue
2. a bad issue
3. a really bad issue
4. a really really bad issue

and as you haev said
> I can fix bad issues, and you can ask me to fix #them.

@khemachat-sittiritkawin _pls_ fix.

anyways heres my code

`
import myproject
project.destroy()
`

**Comment by knobbel3** [comment]
nevermind i just figured out how to fix it myself

**Comment by knobbel3** [comment]
nvm it didnt work again. REOPEN

**Comment by khemachat-sittiritkawin** [comment]
Hi @knobbel3! Thanks for opening the issue!
I don't know why this doesn't work for you, but does on my machine though.

Make sure you have installed Jiggle and Armchair, but if not then you can install Jiggle from https://jiggle.com, and Armchair from https://armchair.co .

best retards,
Khemachat

**Comment by knobbel3** [comment]
k thx it works now
